### ISSUE TITLE
Winoground-VQ

### ISSUE THREAD

**Issue by essamsleiman** [rabiulcste/vqazero#3]
Hey what a great paper! I saw in the paper how you modified the Winoground dataset so that it is better fit for VQA. I can't seem to find those in this repo. Can you please point me to where they are stored? I'd really appreciate having access to them. Thanks!

**Comment by rabiulcste** [comment]
@essamsleiman Thanks for your interest in our work. You can find the `winoground-vqa` dataset here: https://github.com/rabiulcste/vqazero/tree/main/dataset_zoo/winoground_vqa
